export * from "./dashboard/SubDashboard/HorasExtras/Inicio";
export * from "./Bombas/Bombas";
export * from "./Calendario/Calendario";
export * from "./Fontaneros/Fontaneros";
export * from "./Login";
export * from "./Bitacoras/Bitacoras";
export * from "./Calidad_agua/Calidad_agua";
export * from "./Solicitud_vecinos/Vecinos";
export * from "./dashboard/SubDashboard/Tablas/Tablas";
export * from "./dashboard/SubDashboard/Expediente/Expediente";
export * from "./dashboard/SubDashboard/Expediente/Expediente";
export * from "./Vecinos_Solicitud/Svecinos";
export * from "./Settings/Settings";
export * from "./Permisos/Permisos";
export * from "./dashboard/SubDashboard/FinExpediente/Fin_expediente"
export * from "./dashboard/SubDashboard/HorasExtras/Inicio"
export * from "./dashboard/Dashboard"